binop_separator = "Back"
combine_control_expr = false
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
hard_tabs = true
imports_layout = "HorizontalVertical"
imports_granularity="Crate"
use_field_init_shorthand = true
max_width = 80
group_imports = "StdExternalCrate"
wrap_comments = true
