[package]
edition = "2021"
name = "preprocess-macro"
version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
regex = "1"
syn = { version = "2", features = ["full"] }
