[package]
edition = "2021"
name = "preprocess"
version.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
dashmap = "5"
idna = "0.4"
preprocess-macro = { path = "../preprocess-macro" }
regex = "1"
url = "2"
